apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-queue-configmap
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "UrlEndPoint": {
        "PunthaiApi": "http://localhost:53816/Queue/api/v1",
        "SignedApi" :  "http://localhost:53816/Queue/api/v1/Signed"
      }
    }