apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: queue-punthai-frontend-web-viewer-ha
 namespace: queue-punthai-dev
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: queue-punthai-frontend-web
 minReplicas: 1
 maxReplicas: 1
 metrics:
 - type: Resource
   resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: 90
 - type: Resource
   resource:
     name: memory
     target:
       type: AverageValue
       averageValue: 300Mi