kind: Service
apiVersion: v1
metadata:
 name: queue-punthai-frontend-web-service
 namespace: queue-punthai-dev
spec:
 type: ClusterIP
 #LoadBalancer
 #NodePort
 #ClusterIP
 ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
 selector:
   app: queue-punthai-frontend-web